### PR TITLE
Updates to overview page

### PR DESCRIPTION
**Pull request by h-kataria**
https://issues.redhat.com/browse/AA-1163

before
Screen Shot 2022-06-23 at 12 41 26 PM

after
Screen Shot 2022-06-23 at 2 02 36 PM

@trahman73 please review
/cc Tina Yip

### CODE REVIEW

**Comment by trahman73** [comment]
Thanks @h-kataria looking good! Just two points below:
- Can we use this text for the Automation Analytics card? Right now it's just repeating the same as the Hub card.
  
Gain insights into your deployments through visual dashboards and organization statistics, calculate your return on investment, and explore automation processes details.

- Can we horizontally center the "Learn more" link on the Hub card as in the mockups?
Mockups: https://marvelapp.com/prototype/aic093b/screen/86290519

**Comment by tiyiprh** [comment]
@h-kataria Looks great, thank you for updating this! +1 to what @trahman73 mentioned. Would it also be possible to get a link if these changes are staged just to confirm some of the other items from the Jira issue such as the 3. "Critical" & "Warnings" label linking and 4. Navigation? Thank you!

**Comment by h-kataria** [comment]
> Thanks @h-kataria looking good! Just two points below:
> 
>     * Can we use this text for the Automation Analytics card? Right now it's just repeating the same as the Hub card.
> 
> 
> Gain insights into your deployments through visual dashboards and organization statistics, calculate your return on investment, and explore automation processes details.
> 
>     * Can we horizontally center the "Learn more" link on the Hub card as in the mockups?
>       Mockups: https://marvelapp.com/prototype/aic093b/screen/86290519

made requested changes

**Comment by lgalis** [comment]
@h-kataria - code changes look good - just the lint errors need to be addressed

**Review by lgalis — APPROVED** [review]

**Pull request merged**
